version: "3"

services:
  registry:
    build: jenkins-slave
    image: "jenkins-slave"
    expose:
      - "22"
    ports:
      - "1222:22"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_PROXY_SSH_KEY
    #restart: "unless-stopped"