version: "2"

services:
  jenkins-slave:
    image: ${REGISTRY_URL}/jenkins-slave
    extends:
      file: common-service.yml
      service: logging
    volumes: 
    - ${JENKINS_HOME}:/home/slave/jenkins
    ports:
      - "1222:22"
    restart: "unless-stopped"